# The first step of the alternative deploy pipeline
# Instead of building and running on the vm, it builds on github actions
# And then only copies the image to the vm
# Its meant to diminish the workload on the vm which was generating timeout errors.
name: Build and Push to Docker Hub workflow.

on:
  release:
    types:
      - published

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
        #used to check out your repository under $GITHUB_WORKSPACE so your workflow can access it1.
        #It allows your workflow to interact with your code.
        #Without this step, the GitHub Actions runner would not know about the code you want to build
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push Docker image
        # build and push to the dockerhub  your_name/backend_repo_name or frontend_repo_name:github.sha which reflects the commit.
        run: |
            docker build -t ${{ vars.DOCKERHUB_REPOSITORY_BACKEND }}:${{ github.sha }} -t ${{ vars.DOCKERHUB_REPOSITORY_BACKEND }}:latest ./backend
            docker build -t ${{ vars.DOCKERHUB_REPOSITORY_FRONTEND }}:${{ github.sha }} -t ${{ vars.DOCKERHUB_REPOSITORY_FRONTEND }}:latest ./frontend
            docker push ${{ vars.DOCKERHUB_REPOSITORY_BACKEND }}:${{ github.sha }}
            docker push ${{ vars.DOCKERHUB_REPOSITORY_FRONTEND }}:${{ github.sha }}

