# The first step of the alternative deploy pipeline
# Instead of building and running on the vm, it builds on github actions
# And then only copies the image to the vm
# Its meant to diminish the workload on the vm which was generating timeout errors.
name: Build and Push to Docker Hub workflow.

on:
  release:
    types:
      - published

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
        #used to check out your repository under $GITHUB_WORKSPACE so your workflow can access it1.
        #It allows your workflow to interact with your code.
        #Without this step, the GitHub Actions runner would not know about the code you want to build
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        #May not be necessary
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
            echo ${{ vars.DOCKERHUB_REPOSITORY }}
            docker build -t ${{ vars.DOCKERHUB_REPOSITORY }}/backend:${{ github.sha }} ./backend
            docker build -t ${{ vars.DOCKERHUB_REPOSITORY }}/frontend:${{ github.sha }} ./frontend
            echo ${{ vars.DOCKERHUB_REPOSITORY }}/backend:${{ github.sha }}
            docker push ${{ vars.DOCKERHUB_REPOSITORY }}/backend:${{ github.sha }}
            docker push ${{ vars.DOCKERHUB_REPOSITORY }}/frontend:${{ github.sha }}
        #instead of the github sha we could use latest in both files.
