name: Pull Docker Image from hub and Run on vm.

on:
  workflow_dispatch:

jobs:
  pull_and_run:
    runs-on: [self-hosted, production]
    steps:
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_TOKEN }}:latest

      - name: Run Docker image
        run: docker run -d ${{ secrets.DOCKERHUB_TOKEN }}:latest
