name: Pull Docker Image from hub and Runo n vm.

on:
  workflow_dispatch:

jobs:
  pull_and_run:
    runs-on: [self-hosted, production]
    steps:
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull your-dockerhub-username/your-image-name:latest

      - name: Run Docker image
        run: docker run -d your-dockerhub-username/your-image-name:latest
